runtime: python27
api_version: 1
threadsafe: true  # TODO: is it?

handlers:
# TODO: Add favicon.ico
- url: /.*
  script: counter.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
